### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by spynetS** [spynetS/assignment1#6]
- [ ] Fix the exceptions
- [ ] Add command line arguments
- [ ] Change namespaces
- [ ] More operator classes 
- [ ] Create our own stack (feels like that is what she wants)
- [ ] Comments
- [ ] Operator and operand to string method
